In [1]:
from TV_examine.model_assessment import divide_data
from NaiveBayes import *
import numpy as np

## 朴素贝叶斯-垃圾邮件识别
### 数据的预处理
1. 读取每个词
2. 记录每个词的出现次数
3. 转为词向量

In [2]:
def textParse(bigString):
    #将单词以空格划分
    listOfTokens = bigString.split()
    #去除单词长度小于2的无用单词
    return [tok.lower() for tok in listOfTokens if len(tok)>2]

#去列表中重复元素，并以列表形式返回
def createVocaList(dataSet):
    vocabSet = set({})
    #去重复元素，取并集
    for document in dataSet:
        vocabSet = vocabSet | set(document)
    return list(vocabSet)

#统计每一文档（或邮件）在单词表中出现的次数，并以列表形式返回
def setOfWordsToVec(vocabList,inputSet):
    #创建0向量，其长度为单词量的总数
    returnVec = np.zeros(len(vocabList))
    #统计相应的词汇出现的数量
    for word in inputSet:
        if word in vocabList:
            returnVec[vocabList.index(word)] += 1
    return returnVec

In [3]:
docList,classList,x = [],[],[]
for i in range(1, 26):
    # 读取第i篇垃圾文件，并以列表形式返回
    wordList = textParse(open('spam/{0}.txt'.format(i)).read())
    docList.append(wordList)
    classList.append(1)        # 标记文档为垃圾文档
    # 读取第i篇非垃圾文件，并以列表形式返回 
    wordList = textParse(open('ham/{0}.txt'.format(i)).read())
    docList.append(wordList)
    classList.append(0)        # 标记文档为非垃圾文档
vocabList = createVocaList(docList)  # 创建词汇表，不重复
# 将数据向量化
for wordList in docList:
    x.append(setOfWordsToVec(vocabList, wordList))

### 数据划分
使用留出法对数据进行划分，训练集：测试集为3：1

In [4]:
X_train, X_test, y_train, y_test = divide_data.train_test_split(x, classList, 0.25)

In [5]:
nb1 = NaiveBayes()
nb1.fit(X_train, y_train)
res = nb1.predict(X_test)
print("accuracy:", np.sum(res==y_test) / len(res))
y_test, res

accuracy: 0.8461538461538461


(array([1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1]),
 array([1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0]))

## 高数朴素贝叶斯-鸢尾花数据集
- 鸢尾花数据集直接代入模型即可，不用预处理了
- 依然是用留出法划分训练集和测试集

In [6]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target
X_train, X_test, y_train, y_test = divide_data.train_test_split(X, y, 0.2)

In [7]:
nb2 = GaussianNB()
nb2.fit(X_train, y_train)
res = nb2.predict(X_test)
print("accuracy:", np.sum(res==y_test) / len(res))
y_test, res

accuracy: 0.9666666666666667


(array([0, 1, 2, 1, 1, 1, 1, 2, 1, 0, 0, 0, 2, 0, 1, 2, 2, 1, 1, 1, 1, 1,
        2, 1, 1, 1, 2, 0, 2, 0]),
 array([0, 1, 2, 1, 1, 1, 1, 2, 1, 0, 0, 0, 2, 0, 1, 2, 2, 1, 1, 1, 1, 1,
        2, 1, 1, 1, 1, 0, 2, 0]))