In [1]:
from neuralnetwork import *

## 导入数据集
这里没有用MNIST数据集，考核时间不多，调参比较耗费时间，因此用鸢尾花数据集代替好了

In [2]:
iris = load_iris()
X = iris.data
y = iris.target

### 观察数据
- 可以看到X为连续型，y为离散型，神经网络需要把y转化为独热编码。
- 为了加快收敛速度，这里将数据标准化处理

In [3]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
y = pd.get_dummies(y).values
y[:5]

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0]], dtype=uint8)

标准化处理

In [5]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [6]:
stand = preprocessing.Standardization()
X = stand.fit_transform(X)
X[:5]

array([[-0.89767388,  1.01560199, -1.33575163, -1.31105215],
       [-1.13920048, -0.13153881, -1.33575163, -1.31105215],
       [-1.38072709,  0.32731751, -1.39239929, -1.31105215],
       [-1.50149039,  0.09788935, -1.27910398, -1.31105215],
       [-1.01843718,  1.24503015, -1.33575163, -1.31105215]])

## 训练
这里使用留出法进行训练，训练集与测试集之比为4：1

In [7]:
X_train, X_test, y_train, y_test = divide_data.train_test_split(X, y, 0.2)
nn = NeuralNetwork()
nn.fit(X_train, y_train, [4,5,3])
y_pr = nn.predict(X_test)
y2 = np.argmax(y_test, axis=1)
y_pr, y2

(array([0, 0, 1, 0, 1, 0, 0, 0, 2, 0, 0, 1, 1, 0, 2, 0, 2, 2, 2, 0, 1, 0,
        1, 0, 2, 0, 1, 1, 2, 2]),
 array([0, 0, 1, 0, 2, 0, 0, 0, 2, 0, 0, 1, 1, 0, 2, 0, 2, 2, 2, 0, 1, 0,
        1, 0, 2, 0, 2, 1, 2, 2]))

## 评估
准确率为0.933，还行吧..

In [8]:
print('accuracy:',nn.accurate_rate(y_pr, y2))

accuracy: 0.9333333333333333
